import streamlit as st

st.set_page_config(page_title="Proposal Generator", layout="centered")

st.title("🧠 Steve's AI Proposal Generator")

st.markdown("Generate client-ready graphic design proposals in seconds.")

client_name = st.text_input("Client Name")
project_type = st.selectbox("Project Type", ["Logo Design", "Social Media Kit", "Flyer/Poster", "Brand Identity"])
budget = st.text_input("Proposed Budget (e.g., $100)")
timeline = st.text_input("Timeline (e.g., 7 days)")
description = st.text_area("Project Description")

if st.button("🚀 Generate Proposal"):
    st.success("✅ Proposal content generated below!")
    
    st.markdown(f"""
    ## 📝 Proposal Draft
    
    **Client:** {client_name}  
    **Project Type:** {project_type}  
    **Proposed Budget:** {budget}  
    **Timeline:** {timeline}  
    
    ### Project Overview
    {description}
    
    ---
    We look forward to working together and bringing your vision to life.
    
    *Generated by Steve – Powered by Shadow*
    """)
